import type { Metadata } from "next";
import { Inter, Sriracha, Domine } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--inter-font",
});

export const domine = Domine({
  subsets: ["latin"],
  display: "swap",
  variable: "--domine-font",
  preload: true,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${domine.variable} antialiased overflow-hidden`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
